export const AUTH_SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const AUTH_SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const AUTH_SIGN_UP_BEGIN = 'AUTH_SIGN_UP_BEGIN';
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS';
export const AUTH_SIGN_UP_FAILURE = 'AUTH_SIGN_UP_FAILURE';

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const AUTH_REQUEST_INVITATION_BEGIN = 'AUTH_REQUEST_INVITATION_BEGIN';
export const AUTH_REQUEST_INVITATION_SUCCESS = 'AUTH_REQUEST_INVITATION_SUCCESS';
export const AUTH_REQUEST_INVITATION_FAILURE = 'AUTH_REQUEST_INVITATION_FAILURE';

export const AUTH_INVITATION_REDIRECTED = 'AUTH_INVITATION_REDIRECTED';

export const ADMIN_REGISTRATION_SYNC_ROLES_BEGIN = 'ADMIN_REGISTRATION_SYNC_ROLES_BEGIN';
export const ADMIN_REGISTRATION_SYNC_ROLES_SUCCESS = 'ADMIN_REGISTRATION_SYNC_ROLES_SUCCESS';
export const ADMIN_REGISTRATION_SYNC_ROLES_FAILURE = 'ADMIN_REGISTRATION_SYNC_ROLES_FAILURE';

export const ADMIN_REGISTRATION_SYNC_TOKENS_BEGIN = 'ADMIN_REGISTRATION_SYNC_TOKENS_BEGIN';
export const ADMIN_REGISTRATION_SYNC_TOKENS_SUCCESS = 'ADMIN_REGISTRATION_SYNC_TOKENS_SUCCESS';
export const ADMIN_REGISTRATION_SYNC_TOKENS_FAILURE = 'ADMIN_REGISTRATION_SYNC_TOKENS_FAILURE';

export const ADMIN_REGISTRATION_INVITE_BEGIN = 'ADMIN_REGISTRATION_INVITE_BEGIN';
export const ADMIN_REGISTRATION_INVITE_SUCCESS = 'ADMIN_REGISTRATION_INVITE_SUCCESS';
export const ADMIN_REGISTRATION_INVITE_FAILURE = 'ADMIN_REGISTRATION_INVITE_FAILURE';

export const ADMIN_REGISTRATION_RETRACTION_BEGIN = 'ADMIN_REGISTRATION_RETRACTION_BEGIN';
export const ADMIN_REGISTRATION_RETRACTION_SUCCESS = 'ADMIN_REGISTRATION_RETRACTION_SUCCESS';
export const ADMIN_REGISTRATION_RETRACTION_FAILURE = 'ADMIN_REGISTRATION_RETRACTION_FAILURE';

export const ADMIN_ADMINISTRATION_CREATE_ROLE = 'ADMIN_ADMINISTRATION_CREATE_ROLES';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_BEGIN = 'ADMIN_ADMINISTRATION_CREATE_ROLES_BEGIN';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_SUCCESS = 'ADMIN_ADMINISTRATION_CREATE_ROLES_SUCCESS';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_FAILURE = 'ADMIN_ADMINISTRATION_CREATE_ROLES_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_BEGIN =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_SUCCESS =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_FAILURE =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_ROLES_BEGIN = 'ADMIN_ADMINISTRATION_SYNC_ROLES_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_ROLES_SUCCESS = 'ADMIN_ADMINISTRATION_SYNC_ROLES_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_ROLES_FAILURE = 'ADMIN_ADMINISTRATION_SYNC_ROLES_FAILURE';

export const ADMIN_ADMINISTRATION_DELETE_ROLE = 'ADMIN_ADMINISTRATION_DELETE_ROLE';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_BEGIN = 'ADMIN_ADMINISTRATION_DELETE_ROLE_BEGIN';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_SUCCESS = 'ADMIN_ADMINISTRATION_DELETE_ROLE_SUCCESS';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_FAILURE = 'ADMIN_ADMINISTRATION_DELETE_ROLE_FAILURE';

export const ADMIN_LABMANAGEMENT_CREATE_LAB_BEGIN = 'ADMIN_ADMINISTRATION_CREATE_LAB_BEGIN';
export const ADMIN_LABMANAGEMENT_CREATE_LAB_SUCCESS = 'ADMIN_ADMINISTRATION_CREATE_LAB_SUCCESS';
export const ADMIN_LABMANAGEMENT_CREATE_LAB_FAILURE = 'ADMIN_ADMINISTRATION_CREATE_LAB_FAILURE';

