export const AUTH_SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const AUTH_SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const AUTH_SIGN_UP_BEGIN = 'AUTH_SIGN_UP_BEGIN';
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS';
export const AUTH_SIGN_UP_FAILURE = 'AUTH_SIGN_UP_FAILURE';

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const AUTH_REQUEST_INVITATION_BEGIN = 'AUTH_REQUEST_INVITATION_BEGIN';
export const AUTH_REQUEST_INVITATION_SUCCESS = 'AUTH_REQUEST_INVITATION_SUCCESS';
export const AUTH_REQUEST_INVITATION_FAILURE = 'AUTH_REQUEST_INVITATION_FAILURE';

export const AUTH_INVITATION_REDIRECTED = 'AUTH_INVITATION_REDIRECTED';

export const ADMIN_REGISTRATION_SYNC_ROLES_BEGIN = 'ADMIN_REGISTRATION_SYNC_ROLES_BEGIN';
export const ADMIN_REGISTRATION_SYNC_ROLES_SUCCESS = 'ADMIN_REGISTRATION_SYNC_ROLES_SUCCESS';
export const ADMIN_REGISTRATION_SYNC_ROLES_FAILURE = 'ADMIN_REGISTRATION_SYNC_ROLES_FAILURE';

export const ADMIN_REGISTRATION_SYNC_TOKENS_BEGIN = 'ADMIN_REGISTRATION_SYNC_TOKENS_BEGIN';
export const ADMIN_REGISTRATION_SYNC_TOKENS_SUCCESS = 'ADMIN_REGISTRATION_SYNC_TOKENS_SUCCESS';
export const ADMIN_REGISTRATION_SYNC_TOKENS_FAILURE = 'ADMIN_REGISTRATION_SYNC_TOKENS_FAILURE';

export const ADMIN_REGISTRATION_INVITE_BEGIN = 'ADMIN_REGISTRATION_INVITE_BEGIN';
export const ADMIN_REGISTRATION_INVITE_SUCCESS = 'ADMIN_REGISTRATION_INVITE_SUCCESS';
export const ADMIN_REGISTRATION_INVITE_FAILURE = 'ADMIN_REGISTRATION_INVITE_FAILURE';

export const ADMIN_REGISTRATION_RETRACTION_BEGIN = 'ADMIN_REGISTRATION_RETRACTION_BEGIN';
export const ADMIN_REGISTRATION_RETRACTION_SUCCESS = 'ADMIN_REGISTRATION_RETRACTION_SUCCESS';
export const ADMIN_REGISTRATION_RETRACTION_FAILURE = 'ADMIN_REGISTRATION_RETRACTION_FAILURE';

export const ADMIN_ADMINISTRATION_CREATE_ROLE = 'ADMIN_ADMINISTRATION_CREATE_ROLES';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_BEGIN = 'ADMIN_ADMINISTRATION_CREATE_ROLES_BEGIN';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_SUCCESS = 'ADMIN_ADMINISTRATION_CREATE_ROLES_SUCCESS';
export const ADMIN_ADMINISTRATION_CREATE_ROLE_FAILURE = 'ADMIN_ADMINISTRATION_CREATE_ROLES_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_BEGIN =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_SUCCESS =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_FAILURE =
  'ADMIN_ADMINISTRATION_SYNC_PERMISSIONS_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_ROLES_BEGIN = 'ADMIN_ADMINISTRATION_SYNC_ROLES_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_ROLES_SUCCESS = 'ADMIN_ADMINISTRATION_SYNC_ROLES_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_ROLES_FAILURE = 'ADMIN_ADMINISTRATION_SYNC_ROLES_FAILURE';

export const ADMIN_ADMINISTRATION_DELETE_ROLE = 'ADMIN_ADMINISTRATION_DELETE_ROLE';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_BEGIN = 'ADMIN_ADMINISTRATION_DELETE_ROLE_BEGIN';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_SUCCESS = 'ADMIN_ADMINISTRATION_DELETE_ROLE_SUCCESS';
export const ADMIN_ADMINISTRATION_DELETE_ROLE_FAILURE = 'ADMIN_ADMINISTRATION_DELETE_ROLE_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_USERS_BEGIN = 'ADMIN_ADMINISTRATION_SYNC_USERS_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_USERS_SUCCESS = 'ADMIN_ADMINISTRATION_SYNC_USERS_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_USERS_FAILURE = 'ADMIN_ADMINISTRATION_SYNC_USERS_FAILURE';

export const ADMIN_LABMANAGEMENT_CREATE_LAB_BEGIN = 'ADMIN_ADMINISTRATION_CREATE_LAB_BEGIN';
export const ADMIN_LABMANAGEMENT_CREATE_LAB_SUCCESS = 'ADMIN_ADMINISTRATION_CREATE_LAB_SUCCESS';
export const ADMIN_LABMANAGEMENT_CREATE_LAB_FAILURE = 'ADMIN_ADMINISTRATION_CREATE_LAB_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_BEGIN =
  'ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_CREATE_ITEMSET_FAILURE';

export const ADMIN_LAB_MANAGEMENT_SYNC_LABS_BEGIN = 'ADMIN_LAB_MANAGEMENT_SYNC_LABS_BEGIN';
export const ADMIN_LAB_MANAGEMENT_SYNC_LABS_SUCCESS = 'ADMIN_LAB_MANAGEMENT_SYNC_LABS_SUCCESS';
export const ADMIN_LAB_MANAGEMENT_SYNC_LABS_FAILURE = 'ADMIN_LAB_MANAGEMENT_SYNC_LABS_FAILURE';

export const ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_BEGIN = 'ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_BEGIN';
export const ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_SUCCESS =
  'ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_SUCCESS';
export const ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_FAILURE =
  'ADMIN_LAB_MANAGEMENT_ASSIGN_STAFF_FAILURE';

export const ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_BEGIN =
  'ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_BEGIN';
export const ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_SUCCESS =
  'ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_SUCCESS';
export const ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_FAILURE =
  'ADMIN_LAB_MANAGEMENT_UNASSIGN_STAFF_FAILURE';

export const ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_BEGIN = 'ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_BEGIN';
export const ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_SUCCESS =
  'ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_SUCCESS';
export const ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_FAILURE =
  'ADMIN_LAB_MANAGEMENT_SYNC_MANAGERS_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_BEGIN =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMSETS_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_BEGIN = 'ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_FAILURE';
export const ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_CREATE_ITEM_SUCCESS';

export const ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_BEGIN =
  'ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_BEGIN';
export const ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_FAILURE =
  'ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_FAILURE';
export const ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_SUCCESS =
  'ADMIN_ADMINISTRATION_CREATE_SUPERVISOR_SUCCESS';

export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_BEGIN = 'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_SUCCESS = 'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_FAILURE = 'ADMIN_ITEM_MANAGEMENT_SYNC_ITEMS_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_BEGIN =
  'ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_SYNC_LENT_ITEMS_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_BEGIN =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_LOADING';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_SYNC_ITEM_REQUESTS_FAILURE';

export const ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_BEGIN = 'ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_BEGIN';
export const ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_SUCCESS =
  'ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_SUCCESS';
export const ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_FAILURE =
  'ADMIN_ITEM_MANAGEMENT_BORROW_ITEM_FAILURE';

export const ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_BEGIN =
  'ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_BEGIN';
export const ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_SUCCESS =
  'ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_SUCCESS';
export const ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_FAILURE =
  'ADMIN_ADMINISTRATION_SYNC_SUPERVISORS_FAILURE';

export const ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_BEGIN =
  'ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_BEGIN';
export const ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_SUCCESS =
  'ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_SUCCESS';
export const ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_FAILURE =
  'ADMIN_ADMINISTRATION_DELETE_SUPERVISOR_FAILURE';

export const SUPERVISOR_ITEM_MANAGEMENT_SYNC_ITEM_BEGIN =
  'SUPERVISOR_ITEM_MANAGEMENT_SYNC_ITEMSETS_BEGIN';
export const SUPERVISOR_ITEM_MANAGEMENT_SYNC_ITEM_SUCCESS =
  'SUPERVISOR_ITEM_MANAGEMENT_SYNC_iTEM_SUCCESS';
export const SUPERVISOR_ITEM_MANAGEMENT_SYNC_ITEM_FAILURE =
  'SUPERVISOR_ITEM_MANAGEMENT_SYNC_iTEM_FAILURE';

export const SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_BEGIN =
  'SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_BEGIN';
export const SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_SUCCESS =
  'SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_SUCCESS';
export const SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_FAILURE =
  'SUPERVISOR_ITEM_MANAGEMENT_ACCEPT_REQUEST_FAILURE';

export const SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_BEGIN =
  'SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_BEGIN';
export const SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_SUCCESS =
  'SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_SUCCESS';
export const SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_FAILURE =
  'SUPERVISOR_ITEM_MANAGEMENT_REJECT_REQUEST_FAILURE';
export const SOCKET_START_BEGIN = 'SOCKET_START_BEGIN';
export const SOCKET_START_ON_CONNECT = 'SOCKET_START_ON_CONNECT';
export const SOCKET_START_ON_DISCONNECT = 'SOCKET_START_ON_DISCONNECT';
export const SOCKET_START_ON_DEVICE_MESSAGE = 'SOCKET_START_ON_DEVICE_MESSAGE';
export const SOCKET_START_ON_DEVICE_CONNECT = 'SOCKET_START_ON_DEVICE_CONNECT';
export const SOCKET_START_ON_DEVICE_DISCONNECT = 'SOCKET_START_ON_DEVICE_DISCONNECT';
